spring:
# DATASOURCE
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://nas.repetentia.com:33306/rtadb
    username: RTAUSER
    password: R2P2T2NT1@
    hikari:
      maximum-pool-size: 1
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# FILE UPLOAD
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

# Servlet Context Path
server:
  servlet:
    context-path: /web

# MyBatis
mybatis:
  type-aliases-package: com.repetentia.web.*.model
  mapper-locations: sql/mappers/*/*.xml
  mapper-scan-package: com.repetentia

# TILES
tiles:
  settings: classpath:config/tiles/tiles.xml
# Custom Properties Plugin
active:
  site: rta
